DELAY = 70
MENU = True
FONT = 'PressStart2P-Regular'
FONT_SIZE = 17
# ESPACO_ENTRE_MAPAS = 60
DESLOCA_MAPA = 670
DESLOCA_MAPA_VERTICAL = 549
WIDTH = 800           # largura da janela
HEIGHT = 487          # altura da janela
LIM_SUPERIOR = 15
LIM_LATERAL = WIDTH - 205     # limite a direita
PATH_MAPA = 'mapas4'
